### ISSUE TITLE
No se visualizan los colores de los items

### ISSUE THREAD

**Issue by katy-paola** [katy-paola/results-summary-component-main#2]
No se están mostrando dinamicamente los colores de las items, revisar esto con tailwind como podemos solucionarlo.

![Captura de pantalla 2023-06-30 a la(s) 9 43 21 p m](https://github.com/katy-paola/results-summary-component-main/assets/100061789/6b5a9cd6-cde0-4e4a-9b66-820b48d33cf5)

**Comment by pipegoods** [comment]
Si, estoy revisando y no esta compilando el CSS que estamos colocando dinámicamente, por eso no coloca los estilos.

Voy a buscar una solución y crearé un PR.
